ITE SoC SDK: Event
Event
ITE Platform Library
Data Structures
struct ITPEvent
Custom event handle implementation definition.
Functions
ITPEvent * itpEventCreate (void)
Creates event object.
void itpEventDestroy (ITPEvent *event)
Destroys event object.
unsigned long itpEventWaitBits (ITPEvent *event, unsigned long bits, bool clear, bool waitall, unsigned long ms)
Waits event object.
int itpEventSetBits (ITPEvent *event, unsigned long bits)
Sets event object.
Detailed Description
Function Documentation
itpEventCreate()
ITPEvent* itpEventCreate (void)
Creates event object.
Returns
The created event object.
Referenced by TestFunc().
itpEventDestroy()
void itpEventDestroy (ITPEvent * event)
Destroys event object.
Parameters
The event object to destroy.
Referenced by Test_event_wait().
itpEventSetBits()
int itpEventSetBits (ITPEvent * event, unsigned long bits)
Sets event object.
Parameters
event event object to set.
bits event bits to set.
Returns
0 (OK), or -1 (ERROR).
Referenced by Test_event_set().
itpEventWaitBits()
unsigned long itpEventWaitBits (ITPEvent * event, unsigned long bits, bool clear, bool waitall, unsigned long ms)
Waits event object.
Parameters
event event object to wait.
bits event bits to wait.
clear clear event bits on exit or not.
waitall wait all bits or not.
ms timeout value.
Returns
bits to set, or 0 indicates timeout.
Referenced by Test_event_wait().