ITE SoC SDK: POSIX Implementations
POSIX Implementations
ITE Platform Library
Data Structures
struct itpTimer
POSIX timer handle implementation definition.
Macros
#define cpu_to_le32(x) ((uint32_t)(x))
#define cpu_to_be32(x) ithBswap32((uint32_t)(x))
#define le32_to_cpu(x) ((uint32_t)(x))
#define cpu_to_le16(x) ((uint16_t)(x))
#define cpu_to_be16(x) ithBswap16((uint16_t)(x))
#define le16_to_cpu(x) ((uint16_t)(x))
#define be16_to_cpu(x) ithBswap16((uint16_t)(x))
#define be32_to_cpu(x) ithBswap32((uint32_t)(x))
Typedefs
typedef void(* VOIDFUNCPTR) (timer_t timerid, int arg)
Pointer to function returning void.
Functions
int timer_connect (timer_t timerid, VOIDFUNCPTR routine, int arg)
Connects a user routine to the timer signal.
long itpTimevalDiff (struct timeval *starttime, struct timeval *finishtime)
Gets the difference of two timeval, in msec.
uint32_t itpGetTickCount (void)
Gets the tick count, in msec.
uint32_t itpGetTickDuration (uint32_t tick)
Gets the tick duration, in msec.
uint32_t itpGetFreeHeapSize (void)
Gets free heap size, in bytes.
void itpSemPostFromISR (sem_t *sem)
Posts semaphore from ISR.
int itpSemGetValueFromISR (sem_t *sem, int *sval)
Gets semaphore value from ISR.
int itpSemWaitTimeout (sem_t *sem, unsigned long ms)
Waits semaphore with timeout.
int itpMutexLockTimeout (pthread_mutex_t *mutex, unsigned long ms)
Locks mutex with timeout.
void itpTaskNotifyGive (pthread_t pthread)
Notifies task.
void itpTaskNotifyGiveFromISR (pthread_t pthread)
Notifies task from ISR.
int itpTaskNotifyTake (bool clearCountOnExit, long msToWait)
Takes task notify.
void itpTaskSuspend (pthread_t pthread)
Suspends a task.
void itpTaskResume (pthread_t pthread)
Resumes a task.
static uint16_t itpBetoh16 (uint16_t value)
Converts 16-bit big-enddian integer to host 16-bit integer.
static uint32_t itpBetoh32 (uint32_t value)
Converts 32-bit big-enddian integer to host 32-bit integer.
static uint64_t itpBetoh64 (uint64_t value)
Converts 64-bit big-enddian integer to host 64-bit integer.
static uint16_t itpLetoh16 (uint16_t value)
Converts 16-bit little-enddian integer to host 16-bit integer.
static uint32_t itpLetoh32 (uint32_t value)
Converts 32-bit little-enddian integer to host 32-bit integer.
static uint64_t itpLetoh64 (uint64_t value)
Converts 64-bit little-enddian integer to host 64-bit integer.
void itpPrintBacktrace (void)
Print backtrace log.
static size_t strlen_utf8 (const char *s)
Gets the number of UTF-8 word count.
Detailed Description
Macro Definition Documentation
be16_to_cpu
#define be16_to_cpu (x) ithBswap16((uint16_t)(x))
Definition at line 379 of file itp.h.
be32_to_cpu
#define be32_to_cpu (x) ithBswap32((uint32_t)(x))
Definition at line 382 of file itp.h.
cpu_to_be16
#define cpu_to_be16 (x) ithBswap16((uint16_t)(x))
Definition at line 373 of file itp.h.
cpu_to_be32
#define cpu_to_be32 (x) ithBswap32((uint32_t)(x))
Definition at line 364 of file itp.h.
cpu_to_le16
#define cpu_to_le16 (x) ((uint16_t)(x))
Definition at line 370 of file itp.h.
cpu_to_le32
#define cpu_to_le32 (x) ((uint32_t)(x))
Definition at line 361 of file itp.h.
le16_to_cpu
#define le16_to_cpu (x) ((uint16_t)(x))
Definition at line 376 of file itp.h.
le32_to_cpu
#define le32_to_cpu (x) ((uint32_t)(x))
Definition at line 367 of file itp.h.
Typedef Documentation
VOIDFUNCPTR
typedef void(* VOIDFUNCPTR) (timer_t timerid, int arg)
Pointer to function returning void.
Used by POSIX timer.
Definition at line 123 of file itp.h.
Function Documentation
itpBetoh16()
static uint16_t itpBetoh16 (uint16_t value) inline static
Converts 16-bit big-enddian integer to host 16-bit integer.
Parameters
value The big-endian integer.
Returns
The result value.
Definition at line 266 of file itp.h.
itpBetoh32()
static uint32_t itpBetoh32 (uint32_t value) inline static
Converts 32-bit big-enddian integer to host 32-bit integer.
Parameters
value The big-endian integer.
Returns
The result value.
Definition at line 277 of file itp.h.
itpBetoh64()
static uint64_t itpBetoh64 (uint64_t value) inline static
Converts 64-bit big-enddian integer to host 64-bit integer.
Parameters
value The big-endian integer.
Returns
The result value.
Definition at line 288 of file itp.h.
itpGetFreeHeapSize()
uint32_t itpGetFreeHeapSize (void)
Gets free heap size, in bytes.
Returns
free heap size, in bytes.
itpGetTickCount()
uint32_t itpGetTickCount (void)
Gets the tick count, in msec.
Referenced by Test_event_wait().
itpGetTickDuration()
uint32_t itpGetTickDuration (uint32_t tick)
Gets the tick duration, in msec.
Parameters
tick start time
Returns
the difference of the start time and current time, in mesc.
uint32_t startTime = itpGetTickCount();
sleep(5);
printf("duration: %u ms\n", itpGetTickDuration(startTime));
Referenced by Test_event_wait().
itpLetoh16()
static uint16_t itpLetoh16 (uint16_t value) inline static
Converts 16-bit little-enddian integer to host 16-bit integer.
Parameters
value The little-endian integer.
Returns
The result value.
Definition at line 299 of file itp.h.
itpLetoh32()
static uint32_t itpLetoh32 (uint32_t value) inline static
Converts 32-bit little-enddian integer to host 32-bit integer.
Parameters
value The little-endian integer.
Returns
The result value.
Definition at line 310 of file itp.h.
itpLetoh64()
static uint64_t itpLetoh64 (uint64_t value) inline static
Converts 64-bit little-enddian integer to host 64-bit integer.
Parameters
value The little-endian integer.
Returns
The result value.
Definition at line 321 of file itp.h.
itpMutexLockTimeout()
int itpMutexLockTimeout (pthread_mutex_t * mutex, unsigned long ms)
Locks mutex with timeout.
Parameters
mutex mutex handle.
ms timeout value. -1 for infinite.
Returns
0 (OK), or -1 (ERROR).
itpPrintBacktrace()
void itpPrintBacktrace (void)
Print backtrace log.
itpSemGetValueFromISR()
int itpSemGetValueFromISR (sem_t * sem, int * sval)
Gets semaphore value from ISR.
Parameters
sem semaphore handle.
sval return value.
Returns
0 (OK), or -1 (ERROR).
itpSemPostFromISR()
void itpSemPostFromISR (sem_t * sem)
Posts semaphore from ISR.
Parameters
sem semaphore handle.
itpSemWaitTimeout()
int itpSemWaitTimeout (sem_t * sem, unsigned long ms)
Waits semaphore with timeout.
Parameters
sem semaphore handle.
ms timeout value. -1 for infinite.
Returns
0 (OK), or -1 (ERROR).
itpTaskNotifyGive()
void itpTaskNotifyGive (pthread_t pthread)
Notifies task.
Parameters
pthread task to notify.
itpTaskNotifyGiveFromISR()
void itpTaskNotifyGiveFromISR (pthread_t pthread)
Notifies task from ISR.
Parameters
pthread task to notify.
itpTaskNotifyTake()
int itpTaskNotifyTake (bool clearCountOnExit, long msToWait)
Takes task notify.
Parameters
clearCountOnExit task's notification value is reset to 0 or not.
msToWait The maximum time to wait. -1 to wait inifite.
itpTaskResume()
void itpTaskResume (pthread_t pthread)
Resumes a task.
Parameters
pthread task to resume.
Referenced by TestFunc().
itpTaskSuspend()
void itpTaskSuspend (pthread_t pthread)
Suspends a task.
Parameters
pthread task to suspend.
Referenced by TestFunc().
itpTimevalDiff()
long itpTimevalDiff (struct timeval * starttime, struct timeval * finishtime)
Gets the difference of two timeval, in msec.
Parameters
starttime start time
finishtime finish time
Returns
the difference, in msec.
struct timeval startTime, endTime;
gettimeofday(&startTime, NULL);
sleep(5);
gettimeofday(&endTime, NULL);
printf("duration: %ld ms\n", itpTimevalDiff(&startTime, &endTime));
strlen_utf8()
static size_t strlen_utf8 (const char * s) inline static
Gets the number of UTF-8 word count.
Parameters
s The UTF-8 string.
Returns
The word count.
Definition at line 422 of file itp.h.
timer_connect()
int timer_connect (timer_t timerid, VOIDFUNCPTR routine, int arg)
Connects a user routine to the timer signal.
Parameters
timerid timer ID
routine user routine
arg user argument
Returns
0 (OK), or -1 (ERROR) if the timer is invalid or cannot bind the signal handler.
Referenced by Test_timer().