ITE SoC SDK: test_pthread_cond.c File Reference
test_pthread_cond.c File Reference
#include <sys/time.h>
#include <errno.h>
#include <pthread.h>
#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <unistd.h>
Functions
void Test_pthread_cond_timedwait (void)
void * thread (void *arg)
void Test_pthread_cond_wait (void)
void Test_Cond_Others (void)
void * TestFunc (void *arg)
Variables
static pthread_cond_t cond
static pthread_mutex_t mutex
static int footprint = 0
Function Documentation
Test_Cond_Others()
void Test_Cond_Others (void)
Definition at line 100 of file test_pthread_cond.c.
References cond.
Referenced by TestFunc().
Test_pthread_cond_timedwait()
void Test_pthread_cond_timedwait (void)
Definition at line 15 of file test_pthread_cond.c.
References cond, and mutex.
Referenced by TestFunc().
Test_pthread_cond_wait()
void Test_pthread_cond_wait (void)
Definition at line 69 of file test_pthread_cond.c.
References cond, footprint, mutex, thid, and thread().
Referenced by TestFunc().
TestFunc()
void* TestFunc (void * arg)
Definition at line 121 of file test_pthread_cond.c.
References itpInit(), Test_Cond_Others(), Test_pthread_cond_timedwait(), and Test_pthread_cond_wait().
thread()
void* thread (void * arg)
Definition at line 48 of file test_pthread_cond.c.
References cond, footprint, and mutex.
Referenced by Test_pthread_cond_wait().
Variable Documentation
cond
pthread_cond_t cond static
Definition at line 10 of file test_pthread_cond.c.
Referenced by Test_Cond_Others(), Test_pthread_cond_timedwait(), Test_pthread_cond_wait(), and thread().
footprint
int footprint = 0 static
Definition at line 13 of file test_pthread_cond.c.
Referenced by Test_pthread_cond_wait(), and thread().
mutex
pthread_mutex_t mutex static
Definition at line 11 of file test_pthread_cond.c.
Referenced by Test_pthread_cond_timedwait(), Test_pthread_cond_wait(), and thread().