ITE SoC SDK: test_sysstat.c File Reference
test_sysstat.c File Reference
#include <sys/stat.h>
#include <sys/types.h>
#include <fcntl.h>
#include <pthread.h>
#include <stdio.h>
#include <time.h>
#include <unistd.h>
#include "ite/itp.h"
Functions
void Test_fstat ()
void Test_chmod ()
void Test_mkdir ()
void Test_stat ()
void * TestFunc (void *arg)
Function Documentation
Test_chmod()
void Test_chmod ()
Definition at line 39 of file test_sysstat.c.
References stream.
Referenced by TestFunc().
Test_fstat()
void Test_fstat ()
Definition at line 11 of file test_sysstat.c.
Referenced by TestFunc().
Test_mkdir()
void Test_mkdir ()
Definition at line 63 of file test_sysstat.c.
Referenced by TestFunc().
Test_stat()
void Test_stat ()
Definition at line 80 of file test_sysstat.c.
Referenced by TestFunc().
TestFunc()
void* TestFunc (void * arg)
Definition at line 107 of file test_sysstat.c.
References itpInit(), Test_chmod(), Test_fstat(), Test_mkdir(), and Test_stat().