ITE SoC SDK: test_time.c File Reference
test_time.c File Reference
#include <sys/time.h>
#include <errno.h>
#include <pthread.h>
#include <stdio.h>
#include <stdlib.h>
#include <signal.h>
#include <time.h>
#include "ite/itp.h"
Functions
void test_clock ()
void test_difftime ()
void test_mktime ()
void test_time ()
void my_handler (timer_t timerid, int myarg)
void Test_timer (void)
void * TestFunc (void *arg)
Function Documentation
my_handler()
void my_handler (timer_t timerid, int myarg)
Definition at line 80 of file test_time.c.
Referenced by Test_timer().
test_clock()
void test_clock ()
Definition at line 12 of file test_time.c.
Referenced by TestFunc().
test_difftime()
void test_difftime ()
Definition at line 31 of file test_time.c.
Referenced by TestFunc().
test_mktime()
void test_mktime ()
Definition at line 47 of file test_time.c.
Referenced by TestFunc().
test_time()
void test_time ()
Definition at line 71 of file test_time.c.
Referenced by TestFunc().
Test_timer()
void Test_timer (void)
Definition at line 85 of file test_time.c.
References my_handler(), and timer_connect().
Referenced by TestFunc().
TestFunc()
void* TestFunc (void * arg)
Definition at line 107 of file test_time.c.
References itpInit(), test_clock(), test_difftime(), test_mktime(), test_time(), and Test_timer().