ITE SoC SDK: test_stdio.c File Reference
test_stdio.c File Reference
#include <stdio.h>
#include <pthread.h>
#include <unistd.h>
#include "ite/itp.h"
Functions
void test_printf ()
void test_fclose ()
void test_fread ()
void test_fseek ()
void test_fwrite ()
void test_getchar ()
void test_puts ()
void test_remove ()
void test_rename ()
void * TestFunc (void *arg)
Function Documentation
test_fclose()
void test_fclose ()
Definition at line 30 of file test_stdio.c.
References stream.
Referenced by TestFunc().
test_fread()
void test_fread ()
Definition at line 50 of file test_stdio.c.
References stream.
Referenced by TestFunc().
test_fseek()
void test_fseek ()
Definition at line 91 of file test_stdio.c.
References stream.
Referenced by TestFunc().
test_fwrite()
void test_fwrite ()
Definition at line 113 of file test_stdio.c.
References stream.
Referenced by TestFunc().
test_getchar()
void test_getchar ()
Definition at line 140 of file test_stdio.c.
References i.
Referenced by TestFunc().
test_printf()
void test_printf ()
Definition at line 8 of file test_stdio.c.
Referenced by TestFunc().
test_puts()
void test_puts ()
Definition at line 168 of file test_stdio.c.
Referenced by TestFunc().
test_remove()
void test_remove ()
Definition at line 180 of file test_stdio.c.
Referenced by TestFunc().
test_rename()
void test_rename ()
Definition at line 196 of file test_stdio.c.
Referenced by TestFunc().
TestFunc()
void* TestFunc (void * arg)
Definition at line 209 of file test_stdio.c.
References itpInit(), test_fclose(), test_fread(), test_fseek(), test_fwrite(), test_getchar(), test_printf(), test_puts(), test_remove(), and test_rename().