ITE SoC SDK: test_pthread_mutex.c File Reference
test_pthread_mutex.c File Reference
#include <errno.h>
#include <pthread.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
Functions
void * thread_trylock (void *arg)
void Test_pthread_mutex_trylock ()
void * thread_unlock (void *arg)
void Test_pthread_mutex_unlock ()
void Test_Mutex_Others ()
void * TestFunc (void *arg)
Variables
pthread_mutex_t mutex
Function Documentation
Test_Mutex_Others()
void Test_Mutex_Others ()
Definition at line 84 of file test_pthread_mutex.c.
References attr, and mutex.
Referenced by TestFunc().
Test_pthread_mutex_trylock()
void Test_pthread_mutex_trylock ()
Definition at line 21 of file test_pthread_mutex.c.
References mutex, thid, and thread_trylock().
Referenced by TestFunc().
Test_pthread_mutex_unlock()
void Test_pthread_mutex_unlock ()
Definition at line 58 of file test_pthread_mutex.c.
References mutex, thid, and thread_unlock().
Referenced by TestFunc().
TestFunc()
void* TestFunc (void * arg)
Definition at line 107 of file test_pthread_mutex.c.
References itpInit(), Test_Mutex_Others(), Test_pthread_mutex_trylock(), and Test_pthread_mutex_unlock().
thread_trylock()
void* thread_trylock (void * arg)
Definition at line 11 of file test_pthread_mutex.c.
References mutex.
Referenced by Test_pthread_mutex_trylock().
thread_unlock()
void* thread_unlock (void * arg)
Definition at line 46 of file test_pthread_mutex.c.
References mutex.
Referenced by Test_pthread_mutex_unlock().
Variable Documentation
mutex
pthread_mutex_t mutex
Definition at line 9 of file test_pthread_mutex.c.
Referenced by Test_Mutex_Others(), Test_pthread_mutex_trylock(), Test_pthread_mutex_unlock(), thread_trylock(), and thread_unlock().