ITE SoC SDK: test_malloc.c File Reference
test_malloc.c File Reference
#include <pthread.h>
#include <malloc.h>
#include <stdio.h>
#include "ite/itp.h"
Macros
#define TABLE_SIZE 512
Functions
void test_callmalloc ()
void test_mallinfo ()
int func1 (void)
void test_malloc_stats ()
void test_memalign ()
void * TestFunc (void *arg)
Macro Definition Documentation
TABLE_SIZE
#define TABLE_SIZE 512
Definition at line 73 of file test_malloc.c.
Function Documentation
func1()
int func1 (void)
Definition at line 103 of file test_malloc.c.
Referenced by test_malloc_stats().
test_callmalloc()
void test_callmalloc ()
Definition at line 6 of file test_malloc.c.
References i.
Referenced by TestFunc().
test_mallinfo()
void test_mallinfo ()
Definition at line 74 of file test_malloc.c.
References TABLE_SIZE.
Referenced by TestFunc().
test_malloc_stats()
void test_malloc_stats ()
Definition at line 114 of file test_malloc.c.
References func1().
Referenced by TestFunc().
test_memalign()
void test_memalign ()
Definition at line 133 of file test_malloc.c.
Referenced by TestFunc().
TestFunc()
void* TestFunc (void * arg)
Definition at line 144 of file test_malloc.c.
References itpInit(), test_callmalloc(), test_mallinfo(), test_malloc_stats(), and test_memalign().