ITE SoC SDK: test_event.c File Reference
test_event.c File Reference
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <pthread.h>
#include <unistd.h>
#include "ite/itp.h"
Macros
#define BITS_TO_WAIT 0x0101
#define BITS_TO_SET 0x0101
#define MS_TO_WAIT 500
Functions
void * Test_event_wait (void *arg)
void Test_event_set (void)
void * TestFunc (void *arg)
Variables
ITPEvent * ev
uint32_t tickCount
Macro Definition Documentation
BITS_TO_SET
#define BITS_TO_SET 0x0101
Definition at line 9 of file test_event.c.
BITS_TO_WAIT
#define BITS_TO_WAIT 0x0101
Definition at line 8 of file test_event.c.
MS_TO_WAIT
#define MS_TO_WAIT 500
Definition at line 10 of file test_event.c.
Function Documentation
Test_event_set()
void Test_event_set (void)
Definition at line 37 of file test_event.c.
References BITS_TO_SET, ev, and itpEventSetBits().
Referenced by TestFunc().
Test_event_wait()
void* Test_event_wait (void * arg)
Definition at line 16 of file test_event.c.
References BITS_TO_WAIT, ev, itpEventDestroy(), itpEventWaitBits(), itpGetTickCount(), itpGetTickDuration(), MS_TO_WAIT, and tickCount.
Referenced by TestFunc().
TestFunc()
void* TestFunc (void * arg)
Definition at line 48 of file test_event.c.
References ev, itpEventCreate(), itpInit(), Test_event_set(), Test_event_wait(), and thid.
Variable Documentation
ev
ITPEvent* ev
Examples
test_itu/test_button.c, test_itu/test_cursor.c, test_itu/test_jpeg.c, test_itu/test_language.c, test_itu/test_listbox.c, test_itu/test_progressbar.c, test_itu/test_sdl.c, test_itu/test_trackbar.c, test_peripheral/test_ir.c, and test_peripheral/test_keypad.c.
Definition at line 12 of file test_event.c.
Referenced by ituSceneSendEvent(), Test_event_set(), Test_event_wait(), and TestFunc().
tickCount
uint32_t tickCount
Definition at line 13 of file test_event.c.
Referenced by Test_event_wait().