ITE SoC SDK: test_mqueue.c File Reference
test_mqueue.c File Reference
#include <sys/time.h>
#include <errno.h>
#include <mqueue.h>
#include <pthread.h>
#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include "ite/itp.h"
Macros
#define BUFFER 40
Functions
static void * Test_mqueue_receive (void *arg)
void Test_mqueue (void)
void * TestFunc (void *arg)
Variables
static mqd_t queue
static const char * data = "Test Message"
Macro Definition Documentation
BUFFER
#define BUFFER 40
Definition at line 10 of file test_mqueue.c.
Function Documentation
Test_mqueue()
void Test_mqueue (void)
Definition at line 38 of file test_mqueue.c.
References attr, BUFFER, data, queue, and Test_mqueue_receive().
Referenced by TestFunc().
Test_mqueue_receive()
static void* Test_mqueue_receive (void * arg) static
Definition at line 15 of file test_mqueue.c.
References BUFFER, data, and queue.
Referenced by Test_mqueue().
TestFunc()
void* TestFunc (void * arg)
Definition at line 88 of file test_mqueue.c.
References itpInit(), and Test_mqueue().
Variable Documentation
data
const char* data = "Test Message" static
Examples
test_itu/test_jpeg.c, and test_uart/test_uart.c.
Definition at line 13 of file test_mqueue.c.
Referenced by Test_mqueue(), and Test_mqueue_receive().
queue
mqd_t queue static
Definition at line 12 of file test_mqueue.c.
Referenced by Test_mqueue(), and Test_mqueue_receive().