ITE SoC SDK: test_pthread_attr.c File Reference
test_pthread_attr.c File Reference
#include <sys/time.h>
#include <stdio.h>
#include <pthread.h>
Macros
#define MAX_THREADS 256
Functions
void * thread1 (void *arg)
void Test_pthread_attr_setstacksize ()
void Test_pthread_attr_setschedparam ()
void mythread (void)
void Test_pthread_attr_setdetachstate ()
void Test_pthread_attr_getschedparam ()
void * compute_pi (void *s)
void * TestFunc (void *arg)
Variables
int thread_finished =0
int total_hits
int total_misses
int hits [MAX_THREADS][1]
int sample_points
int sample_points_per_thread
int num_threads
Macro Definition Documentation
MAX_THREADS
#define MAX_THREADS 256
Definition at line 125 of file test_pthread_attr.c.
Function Documentation
compute_pi()
void* compute_pi (void * s)
Definition at line 128 of file test_pthread_attr.c.
References hits, i, and sample_points_per_thread.
mythread()
void mythread (void)
Definition at line 58 of file test_pthread_attr.c.
References thread_finished.
Referenced by Test_pthread_attr_setdetachstate().
Test_pthread_attr_getschedparam()
void Test_pthread_attr_getschedparam ()
Definition at line 94 of file test_pthread_attr.c.
References attr.
Referenced by TestFunc().
Test_pthread_attr_setdetachstate()
void Test_pthread_attr_setdetachstate ()
Definition at line 66 of file test_pthread_attr.c.
References mythread(), and thread_finished.
Referenced by TestFunc().
Test_pthread_attr_setschedparam()
void Test_pthread_attr_setschedparam ()
Definition at line 34 of file test_pthread_attr.c.
References attr.
Referenced by TestFunc().
Test_pthread_attr_setstacksize()
void Test_pthread_attr_setstacksize ()
Definition at line 11 of file test_pthread_attr.c.
References attr, thid, and thread1().
Referenced by TestFunc().
TestFunc()
void* TestFunc (void * arg)
Examples
test_itu/test_array.c, test_itu/test_helloworld.c, test_itu/test_stnlcd.c, test_lcd/test_backlight.c, test_lcd/test_lcd.c, test_lcd/test_lcdconsole.c, test_lcd/test_osdconsole.c, test_nor/test_nor.c, test_peripheral/test_ir.c, test_peripheral/test_keypad.c, test_peripheral/test_led.c, and test_peripheral/test_rtc.c.
Definition at line 152 of file test_pthread_attr.c.
thread1()
void* thread1 (void * arg)
Definition at line 5 of file test_pthread_attr.c.
Referenced by Test_pthread_attr_setstacksize().
Variable Documentation
hits
int hits[MAX_THREADS][1]
Definition at line 126 of file test_pthread_attr.c.
Referenced by compute_pi().
num_threads
int num_threads
Definition at line 126 of file test_pthread_attr.c.
sample_points
int sample_points
Definition at line 126 of file test_pthread_attr.c.
sample_points_per_thread
int sample_points_per_thread
Definition at line 126 of file test_pthread_attr.c.
Referenced by compute_pi().
thread_finished
int thread_finished =0
Definition at line 57 of file test_pthread_attr.c.
Referenced by mythread(), and Test_pthread_attr_setdetachstate().
total_hits
int total_hits
Definition at line 126 of file test_pthread_attr.c.
total_misses
int total_misses
Definition at line 126 of file test_pthread_attr.c.