ITE SoC SDK: test_dirent.c File Reference
test_dirent.c File Reference
#include <sys/stat.h>
#include <sys/types.h>
#include <errno.h>
#include <dirent.h>
#include <stdio.h>
#include <pthread.h>
#include "ite/itp.h"
Functions
void traverse (char *fn, int indent)
void test_opendir ()
void test_closedir ()
void test_readdir ()
void test_rewinddir ()
void * TestFunc (void *arg)
Function Documentation
test_closedir()
void test_closedir ()
Definition at line 51 of file test_dirent.c.
Referenced by TestFunc().
test_opendir()
void test_opendir ()
Definition at line 44 of file test_dirent.c.
References traverse().
Referenced by TestFunc().
test_readdir()
void test_readdir ()
Definition at line 72 of file test_dirent.c.
Referenced by TestFunc().
test_rewinddir()
void test_rewinddir ()
Definition at line 92 of file test_dirent.c.
Referenced by TestFunc().
TestFunc()
void* TestFunc (void * arg)
Definition at line 117 of file test_dirent.c.
References itpInit(), test_closedir(), test_opendir(), test_readdir(), and test_rewinddir().
traverse()
void traverse (char * fn, int indent)
Definition at line 10 of file test_dirent.c.
Referenced by test_opendir().