ITE SoC SDK: test_unistd.c File Reference
test_unistd.c File Reference
#include <sys/stat.h>
#include <sys/time.h>
#include <sys/types.h>
#include <fcntl.h>
#include <pthread.h>
#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include "ite/itp.h"
Functions
void Test_write ()
void Test_read ()
int Test_lseek ()
void Test_getcwd (char new_dir[])
void Test_rmdir (char new_dir[])
void Test_usleep ()
void Test_sleep ()
void * TestFunc (void *arg)
Function Documentation
Test_getcwd()
void Test_getcwd (char new_dir[])
Definition at line 72 of file test_unistd.c.
Referenced by TestFunc().
Test_lseek()
int Test_lseek ()
Definition at line 52 of file test_unistd.c.
Referenced by TestFunc().
Test_read()
void Test_read ()
Definition at line 34 of file test_unistd.c.
Referenced by TestFunc().
Test_rmdir()
void Test_rmdir (char new_dir[])
Definition at line 99 of file test_unistd.c.
Referenced by TestFunc().
Test_sleep()
void Test_sleep ()
Definition at line 141 of file test_unistd.c.
Referenced by TestFunc().
Test_usleep()
void Test_usleep ()
Definition at line 125 of file test_unistd.c.
Referenced by TestFunc().
Test_write()
void Test_write ()
Definition at line 11 of file test_unistd.c.
Referenced by TestFunc().
TestFunc()
void* TestFunc (void * arg)
Definition at line 154 of file test_unistd.c.
References itpInit(), Test_getcwd(), Test_lseek(), Test_pthread_attr_getschedparam(), Test_pthread_attr_setdetachstate(), Test_pthread_attr_setschedparam(), Test_pthread_attr_setstacksize(), Test_read(), Test_rmdir(), Test_sleep(), Test_usleep(), and Test_write().
Referenced by main().